/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { ForecastIcon as ForecastIcon } from './components/icon/icon';

interface HTMLForecastIconElement extends ForecastIcon, HTMLElement {
}
declare var HTMLForecastIconElement: {
  prototype: HTMLForecastIconElement;
  new (): HTMLForecastIconElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "forecast-icon": HTMLForecastIconElement;
  }
  interface ElementTagNameMap {
      "forecast-icon": HTMLForecastIconElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "forecast-icon": JSXElements.ForecastIconAttributes;
      }
  }
  namespace JSXElements {
      export interface ForecastIconAttributes extends HTMLAttributes {
        
          name?: any,
          size?: any
      }
  }
}

